# Generated by Django 3.2.3 on 2021-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rank',
            field=models.PositiveIntegerField(choices=[(1, 'ISTJ'), (2, 'ISFJ'), (3, 'INFJ'), (4, 'INTJ'), (5, 'ISTP'), (6, 'ISFP'), (7, 'INFP'), (8, 'INTP'), (9, 'ESTP'), (10, 'ESFP')], default=5),
        ),
    ]
