# Generated by Django 3.2.3 on 2021-11-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='like_user',
        ),
    ]
